import { NavigationEvents } from "@/components/navigation";
import DashboardLayout from "./components/dashboard-layouts";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <DashboardLayout>{children}</DashboardLayout>;
}
